version: '3.8'
services:
  app:
    build: .
    ports:
      - "83:83"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/productos?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "productos.jar"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: productos
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5