version: '1'
services:
  microservice:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@veguizp6irortseo_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=BDY2201_FS1
      - spring.datasource.password=ActSum.S5_BDY
    restart: always
    